name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    env:
      # Use the PAT secret for cross-repository permissions if needed,
      # or the default token if publishing to the same repo.
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libasound2t64 libxtst-dev libxss1 libnss3 xvfb

      - name: Install dependencies
        run: npm install

      # --- DEFINITIVE FIX: OS-SPECIFIC PUBLISH STEPS ---

      - name: Build and Publish on Windows
        if: runner.os == 'Windows'
        # Explicitly tell Forge to ONLY use the squirrel (Windows) maker
        run: npx electron-forge publish --targets @electron-forge/maker-squirrel

      - name: Build and Publish on macOS
        if: runner.os == 'macOS'
        # Explicitly tell Forge to ONLY use the dmg (macOS) maker
        run: npx electron-forge publish --targets @electron-forge/maker-dmg

      - name: Build and Publish on Linux
        if: runner.os == 'Linux'
        # Explicitly tell Forge to ONLY use the deb and rpm (Linux) makers
        run: xvfb-run --auto-servernum npx electron-forge publish --targets @electron-forge/maker-deb,@electron-forge/maker-rpm